CONFIG = {
    "repetition_time": "json_RepetitionTime",
    "coil_string": "json_CoilString",
    "nifti_dim": "nifti_dim",
    "nifti_pixdim": "nifti_pixdim",
    "nifti_exists": "NIfTI_exists",
    "json_exists": "JSON_exists",
    "percent_phase_fov": "json_PercentPhaseFOV",
    "magnetic_field_strength": "json_MagneticFieldStrength",
    "manufacturer_model": "json_ManufacturersModelName",
    "institution_name": "json_InstitutionName",
    "mr_acquisition_type": "json_MRAcquisitionType",
    "slice_thickness": "json_SliceThickness",
    "spacing_between_slices": "json_SpacingBetweenSlices",
    "echo_time": "json_EchoTime",
    "flip_angle": "json_FlipAngle",
    "percent_sampling": "json_PercentSampling",
    "echo_train_length": "json_EchoTrainLength",
    "acquisition_matrix_pe": "json_AcquisitionMatrixPE",
    "phase_encoding_direction": "json_PhaseEncodingDirection",
    "mr_acquisition_freq_encoding": "dicom_MRAcquisitionFrequencyEncodingSteps",
    "phase_encoding_axis": "json_PhaseEncodingAxis",
    "SeriesDate": "dicom_SeriesDate",
    "PTID": "Subject_ID",
    "T1w_exists": "T1w_exists" 
}